#' Getting Data from Mortality Tables hosted on http://mort.soa.org
#'
#' mortalitytable access to the website that contains mortality table and grab the information for you.
#'
#' @param num The number of the table you want to access in the website
#' @return A list contains various information in the table you have asked
#' @export
mortalitytable<-function(num){
  # In the following line you can see that I am using the directory named Tables.
  # (now you know how to change it to anything else)
  doc<-XML::xmlParse(paste("Tables/t",as.character(num),".xml",sep=""),getDTD=F);
  r<-XML::xmlRoot(doc);

  Table<-list(number=as.integer(unlist(lapply(XML::xpathApply(r,"ContentClassification/TableIdentity"), XML::xmlValue))));
  Table<-c(Table,name=unlist(lapply(XML::xpathApply(r,"ContentClassification/TableName"), XML::xmlValue)));
  Table<-c(Table,layout="",usage="",nation="");
  Table[3:5]=unlist(lapply(XML::xpathApply(r,"ContentClassification/KeyWord"), XML::xmlValue));
  Table<-c(Table,select.minage=0, select.maxage=100, select.ageinc=1);
  Table[6]=as.integer(unlist(lapply(XML::xpathApply(r[[2]],"MetaData/AxisDef[@id='Age']/MinScaleValue"), XML::xmlValue)));
  Table[7]=as.integer(unlist(lapply(XML::xpathApply(r[[2]],"MetaData/AxisDef[@id='Age']/MaxScaleValue"), XML::xmlValue)));
  Table[8]=as.integer(unlist(lapply(XML::xpathApply(r[[2]],"MetaData/AxisDef[@id='Age']/Increment"),     XML::xmlValue)));
  Table<-c(Table, select.mindur=0, select.maxdur=100, select.durinc=1);
  i<-2;
  if (Table[3]=="Select"){
    Table[9]=as.integer(unlist(lapply(XML::xpathApply(r[[i]],"MetaData/AxisDef[@id='Duration']/MinScaleValue"),XML::xmlValue)));
    Table[10]=as.integer(unlist(lapply(XML::xpathApply(r[[i]],"MetaData/AxisDef[@id='Duration']/MaxScaleValue"),XML::xmlValue)));
    Table[11]=as.integer(unlist(lapply(XML::xpathApply(r[[i]],"MetaData/AxisDef[@id='Duration']/Increment"),XML::xmlValue)));
    i<-i+1;
  }
  Table<-c(Table,ult.minage=0,ult.maxage=100,ult.ageinc=1);
  Table[12]=as.integer(unlist(lapply(XML::xpathApply(r[[i]],"MetaData/AxisDef[@id='Age']/MinScaleValue"), XML::xmlValue)));
  Table[13]=as.integer(unlist(lapply(XML::xpathApply(r[[i]],"MetaData/AxisDef[@id='Age']/MaxScaleValue"), XML::xmlValue)));
  Table[14]=as.integer(unlist(lapply(XML::xpathApply(r[[i]],"MetaData/AxisDef[@id='Age']/Increment"), XML::xmlValue)));
  sel.numages<-(Table$select.maxage-Table$select.minage)/Table$select.ageinc+1;
  sel.numdur<-(Table$select.maxdur-Table$select.mindur)/Table$select.durinc+1;
  if (Table[3]=="Select"){
    qsel<-matrix(0,sel.numages,sel.numdur);
    for (i in 1:sel.numages){
      j<-Table$select.minage + (i-1)*Table$select.ageinc;
      mystr=paste("//Values/Axis[@t=",as.character(j),"]/Axis/Y",sep="");
      qsel[i,]<-as.double(unlist(lapply(XML::xpathApply(r[[2]],mystr), XML::xmlValue)))
    }
  }
  qult<-as.double(unlist(lapply(XML::xpathApply(r[[i]],"//Values/Axis/Y"), XML::xmlValue)));
  if (Table[3]=="Select") {
    Table<-c(Table,list(qsel=qsel,qult=qult));
  }
  else {
    Table<-c(Table,list(qult=qult));
  }
  Table
}


#' Getting the mortality rates from a mortality table
#'
#' Access to mortality rate in a mortality table
#'
#' @param tab A table generated by `mortalitytable` function.
#' @param age staring age
#' @param dur duration
#' @return A list contains various information in the table you have asked
#' @export
mortalitytableq<-function(tab, age, dur){
  if (dur>0){
    selrow<-(age-tab$select.minage)/tab$select.ageinc+1;
    selcol<-(dur-tab$select.mindur)/tab$select.durinc+1;
    myq<-tab$qsel[selrow,selcol:tab$select.maxdur];
    ultage<-age+tab$select.maxdur;
    ultcol<-(ultage-tab$ult.minage)/tab$ult.ageinc+1;
    if (ultcol<=length(tab$qult)) {
      myq<-c(myq,tab$qult[ultcol:length(tab$qult)])
    }
  }
  else {
    ultcol<-(age-tab$ult.minage)/tab$ult.ageinc+1;
    myq<-tab$qult[ultcol:length(tab$qult)]
  }
  if (max(is.na(myq))>0) {
    myq<-myq[1:min((1:length(myq))[is.na(myq)])-1]
  }
  myq
}
